### ISSUE TITLE
Move-out date before move-in date

### ISSUE THREAD

**Issue by Ryashi** [scg-unibe-ch/ese2016-team2#28]
As of your release v2.1, it is possible to set the **move-out date earlier than the move-in date**.

So i.e. I can set the move-in date to be "14.11.2016", but then I can choose the move-out date to be "14.11.2015" which results in a logical inconsitency.

![dates](https://cloud.githubusercontent.com/assets/15871260/20264388/8f6ae4c8-aa6b-11e6-848f-3290a26b1c8d.png)

Check [Pull Request #29](https://github.com/scg-unibe-ch/ese2016-team2/pull/29)

**Comment by gourmetseasoningsake** [comment]
Thanks @Ryashi 

@joelfimian @JulianSchuhmacher 
I think, i'll **add some sort of js form validator** (->trello). so a user won't be able to submit unless inputs/the form is valid. Also, users are notified about invalid input "onblur". In other words, when a user changes the value and leaves the input element, the value will be validated. If it's invalid, the user will be notified, else nix. This does not mean that we shouldn't deal with it in the back-end.

**Comment by joelfimian** [comment]
combined in Issu "Open Tasks"
