### ISSUE TITLE
Wrong end-time while placing an auction crashes server

### ISSUE THREAD

**Issue by javinator** [scg-unibe-ch/ese2016-team2#32]
If you don't enter the end time in the correct format, you get a failure with a null pointer exception. Additionally there is no way to know in which format to input the time. (hh:mm)

![end-time](https://raw.githubusercontent.com/scg-unibe-ch/ese2016-team8/master/baseProject/task%204%20-%20bug%20hunting/5/endtime.png)

![error](https://raw.githubusercontent.com/scg-unibe-ch/ese2016-team8/master/baseProject/task%204%20-%20bug%20hunting/5/exception.png)

Failure is due to accessing a substring which doesn't exists if end time is not at least 5 characters long in AuctionService.java 

![auctionservice](https://raw.githubusercontent.com/scg-unibe-ch/ese2016-team8/master/baseProject/task%204%20-%20bug%20hunting/5/java.png)

**Comment by joelfimian** [comment]
combined in Issu "Open Tasks"
