### ISSUE TITLE
Wrong character encoding

### ISSUE THREAD

**Issue by javinator** [scg-unibe-ch/ese2016-team2#33]
Umlaut are not displayed correctly if used in title or description

For example, 'Mäine Hütte' becomes

![](https://raw.githubusercontent.com/scg-unibe-ch/ese2016-team8/master/baseProject/task%204%20-%20bug%20hunting/2/encoding.png)

Has something to do with UTF-8 encoding not correctly used.

**Comment by gourmetseasoningsake** [comment]
Thanks @javinator 

.. solved in 2.2
