### ISSUE TITLE
Sorting results doesn't sort in correct order

### ISSUE THREAD

**Issue by javinator** [scg-unibe-ch/ese2016-team2#34]
When sorting for prices, the sort method in the search results sorts lexicographically, so if you chose price ascending, 1100CHF comes before 360CHF

![](https://raw.githubusercontent.com/scg-unibe-ch/ese2016-team8/master/baseProject/task%204%20-%20bug%20hunting/6/sorting.png)

**Comment by gourmetseasoningsake** [comment]
Cheers.

... solved in 2.2
