### ISSUE TITLE
Wrong char encoding in AdTestDataSaver.java

### ISSUE THREAD

**Issue by gourmetseasoningsake** [scg-unibe-ch/ese2016-team2#5]
Although wrong char encoding was removed in such a way that code runs again, there are still a bunch of diamonds (�) in strings. Have a look at [AdTestDataSaver.java](https://github.com/scg-unibe-ch/ese2016-team2/blob/master/baseProject/src/test/java/ch/unibe/ese/team1/test/testData/AdTestDataSaver.java) starting from Line 141 onwards:

141> adBern2.setStreet("L�ngassstr. 40");
...

So, i guess, some editor configs are not set to UTF-8.

**Comment by JulianSchuhmacher** [comment]
Encoding error when submitting placeAdForm.

**Comment by gourmetseasoningsake** [comment]
Still.

**Comment by gourmetseasoningsake** [comment]
I finally took the time to look into this. I do not have this issue anymore.
@JulianSchuhmacher Adding the following filter to web.xml solved the issue for POST as for placeAd:
```
<filter>
  <filter-name>encoding-filter</filter-name>
  <filter-class>
      org.springframework.web.filter.CharacterEncodingFilter
  </filter-class>
  <init-param>
    <param-name>encoding</param-name>
    <param-value>UTF-8</param-value>
  </init-param>
  <init-param>
    <param-name>forceEncoding</param-name>
    <param-value>true</param-value>
  </init-param>
</filter>
<filter-mapping>
  <filter-name>encoding-filter</filter-name>
  <url-pattern>/*</url-pattern>
</filter-mapping>
```

Also, the following compiler encoding in pom.xml does not work for me:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.0</version>
  <configuration>
    <source>1.8</source>
    <target>1.8</target>
    <encoding>ISO-8859-1</encoding>
  </configuration>
</plugin>
```

I've changed it to utf-8:
```
<plugin>
  <groupId>org.apache.maven.plugins</groupId>
  <artifactId>maven-compiler-plugin</artifactId>
  <version>3.0</version>
  <configuration>
    <source>1.8</source>
    <target>1.8</target>
    <encoding>UTF-8</encoding>
  </configuration>
</plugin>
```

I also checked that STS (or Eclipse) has UTF-8 set for the workspace. I think it's the default encoding, though. But still.

**Comment by gourmetseasoningsake** [comment]
UPDATE: I've changed all of the above in developFrontEnd and will push soon.

**Comment by gourmetseasoningsake** [comment]
Just for reference, the diamonds and shti also caused failure of the following:

```
public void triggerAlerts(Advertisement ad) {
		int adPrice = ad.getPrize();
		Iterable<Alert> alerts = alertDao.findByPriceGreaterThan(adPrice - 1);

		// loop through all ads with matching city and price range, throw out
		// mismatches
		Iterator<Alert> alertIterator = alerts.iterator();
		while (alertIterator.hasNext()) {
			Alert alert = alertIterator.next();
			if (typeMismatchWith(ad, alert) || radiusMismatchWith(ad, alert)
					|| ad.getUser().equals(alert.getUser()))
				alertIterator.remove();
		}
...
```
